#!/bin/sh
set -x

test -d acdir || mkdir -p acdir
if [ "$(which aclocal)" ] && [ "$(which autoconf)" ] && [ "$(which automake)" ]; then
    aclocal
    automake --add-missing --copy
    autoconf
else
    echo "Some components not found: aclocal/automake/autoconf"
fi
